#!/usr/bin/bash
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

git update-server-info

DIR=${GIT_DIR#/repos}
EDIR=$(systemd-escape "${DIR}")

echo "starting sync to the remote!"
systemctl start --no-block "sync@${EDIR}.service"
