#!/usr/bin/bash
#
# This is c

git update-server-info

ABS_GIT_DIR=$(realpath --canonicalize-missing --no-symlinks "${GIT_DIR}")
DIR=${ABS_GIT_DIR#/repos}
DIR=$(systemd-escape "${DIR}")
SRV="sync@${DIR}.service"

echo "=========================================" >&2
echo "starting sync to the remote as ${SRV}" >&2
git remote get-url origin >&2
systemctl start --no-block "$SRV"
echo "=========================================" >&2
