<?php

return array(
	'dbtableprefix' => '',
	'default_language' => 'zh_CN',
	'default_locale' => 'zh_CN',
	'knowledgebaseenabled' => false,
	'remember_login_cookie_lifetime' => 60 * 60 * 24 * 30,
	'session_lifetime' => 60 * 60 * 24 * 30,
	'session_keepalive' => false,
	'token_auth_enforced' => false,
	'trashbin_retention_obligation' => '7,30',
	'connectivity_check_domains' => array('google.com'),
	'updatechecker' => false,
	'check_for_working_htaccess' => false,
	'enable_previews' => true,
	'enabledPreviewProviders' => array(
		'OC\Preview\Illustrator',
		'OC\Preview\OpenDocument',
		'OC\Preview\PDF',
		'OC\Preview\SVG',
		'OC\Preview\Font',
		'OC\Preview\PNG',
		'OC\Preview\JPEG',
		'OC\Preview\GIF',
		'OC\Preview\HEIC',
		'OC\Preview\BMP',
		'OC\Preview\XBitmap',
		'OC\Preview\MP3',
		'OC\Preview\TXT',
		'OC\Preview\MarkDown',
	),
	'blacklisted_files' => array(
		'.htaccess',
		'.recycle',
		'$RECYCLE.BIN',
		'found.000',
		'System Volume Information',
		'OneDriveTemp',
		'thumbs.db',
	),
	'config_is_read_only' => false,
	'mail_domain' => 'gongt.me',
	'mail_smtpmode' => 'smtp',
	'mail_smtpname' => 'NextCloud Notify',
	'mail_from_address' => 'nextcloud@gongt.me',
	'mail_smtphost' => 'smtp.mailgun.org',
	'mail_smtpsecure' => 'tls',
	'mail_smtpport' => 587,
	'mail_smtptimeout' => 30,
	'mail_smtpauth' => true,
	'mail_smtpauthtype' => 'LOGIN',
	'debug' => true,
	'trusted_domains' => array(
		'localhost',
	),
);
