#!/usr/bin/env bash

set -Eeuo pipefail

### 更新incubator-pagespeed-ngx.tar.xz文件
# why：pagespeed需要直接下载github release，而不是克隆源码（否则会非常麻烦）
# 但是github release在aws上，并且pagespeed依赖位于dl.google.com上的psol。
# 所以由于众所周知的原因，需要提前在有代理的环境下载源码并提交

die() {
    echo "$@" >&2
    exit 1
}

ROOT="$(dirname "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")"

cd "$ROOT/source/modules"

for i in */.git ; do
	cd "$(dirname "$i")"
	echo "Updating: $(dirname "$i")..."
	{
		git checkout master
		git reset --hard
		git pull
	} || die "Failed."
	cd ..
done

cd ../nginx
echo "Updating: nginx core..."
{
	git checkout master
	git reset --hard
	git pull
} || die "Failed."

echo "Done."
