language: zh-CN
timezone: '	Asia/Chongqing'
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

admin:
  deployCommand: /usr/bin/hexo-deploy
