#!/bin/bash

set -Eeuo pipefail

export http_proxy="" https_proxy="" HTTP_PROXY="" HTTPS_PROXY=""

SAVE_FILE=/storage/save.ip.out
SAVE_IP_FILE=/storage/save.ip
CURRENT_IP_OUTPUT=$(ip addr | grep inet6 | grep global | awk '{print $2}' | sed -E 's#/\d+$##g')

echo "current ip address:"
for i in $CURRENT_IP_OUTPUT ; do
    echo "  * $i"
done

if [[ -e "$SAVE_FILE" ]]; then
    if [[ "$(<$SAVE_FILE)" == "$CURRENT_IP_OUTPUT" ]]; then
        echo "current IP output not change"
        exit 0
    else
        echo "    saved IP output has change. saved was:"
        for i in $(<$SAVE_FILE) ; do
            echo "      * $i"
        done
    fi
else
    echo "    no saved IP output."
fi



echo "ensure network connection..."
I=0
while true ; do
    RES=$(nslookup ns1.he.net | tail -n +3 | grep Address | sed 's/Address: /nameserver /g')
    if [[ -n "$RES" ]]; then
        break
    fi
    sleep 1
    I=$((I + 1))
    
    if [[ "$I" -gt 5 ]] ; then
        echo 'Failed resolve domain, maybe network issue.'
        echo '======================'
        ip addr
        echo '======================'
        cat /etc/resolv.conf
        echo '======================'
        exit 1
    fi
    
    echo "retry ($I)..."
done
echo "dns resolve ok:
$RES"
echo "$RES" > /etc/resolv.conf

function call_curl() {
    echo "------------------ try $1..." >&2
    local OUT
    OUT=$(/usr/bin/curl --no-progress-meter --verbose -6 "$1")
    echo "$OUT" >&2
    echo "------------------" >&2
    if [[ -z "$OUT" ]]; then
        return 1
    fi
    for i in $CURRENT_IP_OUTPUT ; do
        if echo "$OUT" | grep -q "$i" ; then
            echo "$i"
            return 0
        fi
    done
    return 1
}

sleep 5

function request_url() {
    call_curl http://checkip.dns.he.net || \
    call_curl https://api6.ipify.org || \
    call_curl http://checkip.dyndns.org || \
    call_curl https://checkip.gongt.me || \
    echo ""
}

CNT=$(echo "$CURRENT_IP_OUTPUT" | wc -l)
if [[ "$CNT" -ne 1 ]]; then
    echo "failed to detect ip from interface (got $CNT address, but want 1 only)"
    CURRENT_IP=$(request_url)
else
    echo "use it"
    CURRENT_IP=$CURRENT_IP_OUTPUT
fi

if [[ -z "$CURRENT_IP" ]] ; then
    echo 'failed to get any ip address' >&2 ; exit 1
fi

echo "current ip address is: $CURRENT_IP"

if [[ -e "$SAVE_IP_FILE" ]] ; then
    if [[ "$(<$SAVE_IP_FILE)" == "$CURRENT_IP" ]]; then
        echo "current IP not change ($CURRENT_IP)."
        exit 0
    else
        echo "    saved was: $(<$SAVE_IP_FILE)"
    fi
else
    echo "    no saved IP."
fi

echo "request update api..."
/usr/bin/curl --no-progress-meter --silent -6 "https://dyn.dns.he.net/nic/update" \
-d "hostname=${DDNS_HOST}" \
-d "password=${DSNS_KEY}"

echo ""
echo "update done."

echo -n "$CURRENT_IP_OUTPUT" > "$SAVE_FILE"
echo -n "$CURRENT_IP" > "$SAVE_IP_FILE"
echo "state saved."
