name: Build Image
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to build'
        required: true
env:
  NODE_ENV: production
  http_proxy: http://proxy-server.:3271
  CI: github-actions
jobs:
  build:
    runs-on: [self-hosted, linux]
    name: 'Build image'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          clean: true
          fetch-depth: 0
      - name: 'Cleanup'
        run: node common/scripts/install-run-rush.js install
      - name: 'Build'
        run: node common/scripts/install-run-rush.js build --verbose
