name: Cancel All
on:
  workflow_dispatch:
jobs:
  cancel:
    name: Cancel All Runs
    runs-on: ubuntu-latest
    steps:
      - name: cancel running workflows
        uses: GongT/cancel-previous-workflows@4f68a25b64f2aeec495c67487f3a7add12eaf81a
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CANCEL_ALL: yes
