name: Cancel All
on:
  workflow_dispatch:
jobs:
  cancel:
    name: Cancel All Runs
    runs-on: ubuntu-latest
    steps:
      - name: cancel running workflows
        uses: GongT/cancel-previous-workflows@54c4d6271c0035e977e9a3a44877160b6950929e
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CANCEL_ALL: yes
