name: Cancel All
on:
  workflow_dispatch:
jobs:
  cancel:
    name: Cancel All Runs
    runs-on: ubuntu-latest
    steps:
      - name: 'Delete cache images'
        shell: bash
        run: ./_scripts_/clean-cache.sh
