name: "gamedisk"
on:
  workflow_dispatch:
  push:
    paths:
    - 'gamedisk/**'
    branches:
    - master
env:
  NODE_ENV: production
  CI: github-actions
jobs:
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: cancel running workflows
        uses: GongT/cancel-previous-workflows@54c4d6271c0035e977e9a3a44877160b6950929e
        env:
          GITHUB_TOKEN: ${{ github.token }}
  build:
    name: 'standalone build gamedisk image'
    runs-on: [self-hosted, linux]
    env:
      http_proxy: http://proxy-server.:3271
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          clean: true
          fetch-depth: 0
      - name: 'Fetch exists image from docker'
        shell: bash
        run: podman pull "docker://docker.io/gongt/gamedisk"
        continue-on-error: true
      - name: 'Build Image'
        run: bash -e _scripts_/ci-single-build.sh gamedisk
      - name: 'Publish to docker hub'
        shell: bash
        env:
          PASSWD: ${{ secrets.DockerPassword }}
        run: podman push "${{ env.LAST_COMMITED_IMAGE }}" --creds "gongt:$PASSWD" "docker://docker.io/gongt/gamedisk"
