name: "docker-registry"
on:
  workflow_dispatch:
  push:
    paths:
    - 'docker-registry/**'
    - '.github/workflows/generated-build-docker-registry.yaml'
    # - common
    branches:
    - master
env:
  NODE_ENV: production
  CI: github-actions
jobs:
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: cancel running workflows
        uses: GongT/cancel-previous-workflows@d71dfdad6d8b1d2e5896e4be6484a1bf727560ec
        env:
          DELETE: "yes"
          GITHUB_TOKEN: ${{ github.token }}
  build:
    name: 'standalone build docker-registry image'
    runs-on: [self-hosted, linux]
    env:
      http_proxy: http://proxy-server.:3271
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        env:
          http_proxy: http://proxy-server.:3271
        with:
          submodules: 'recursive'
          clean: true
          fetch-depth: 0
      - name: 'Fetch exists image from docker'
        shell: bash
        run: podman pull "docker://docker.io/gongt/docker-registry"
        # continue-on-error: true
        env:
          http_proxy: ''
      - name: 'Build Image'
        run: bash -e _scripts_/ci-single-build.sh docker-registry
      - name: 'Publish to docker hub'
        shell: bash
        env:
          PASSWD: ${{ secrets.DockerPassword }}
          http_proxy: ''
        run: ./_scripts_/retry.sh podman push "${{ env.LAST_COMMITED_IMAGE }}" --creds "gongt:$PASSWD" "docker://docker.io/gongt/docker-registry"
